FROM node:13.12.0-alpine

WORKDIR /app/frontend

RUN npm install --silent
RUN npm install react-scripts -g --silent

ENV PATH /app/node_modules/.bin:$PATH

COPY ./package.json .
COPY ./package-lock.json .

COPY . .

CMD ["npm", "start"] 