version: "3.7"

services:
  backend_django:
    container_name: backend_django_dev
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
  backend_fastapi:
    container_name: backend_fastapi_dev
    build: 
      context: ./backendfastapi
      dockerfile: Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 80
    ports:
      - 80:80
  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    container_name: postgresql_bue_dev
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bue_strenge_gemmer
      - POSTGRES_PASSWORD=bue_strenge_gemmer
      - POSTGRES_DB=bue_strenge_gemmer_dev
volumes:
  postgres_data: