version: '3.7'

services:
  nginx: 
    restart: unless-stopped
    container_name: nginx_bue_prod
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/backend/backend/django_static
      - ./nginx:/etc/nginx/default.conf
    depends_on: 
      - backend  
  backend:
    restart: unless-stopped
    container_name: backend_bue_prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 & celery worker --app=arrows.tasks
    volumes:
      - static_volume:/app/backend/backend/django_static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on: 
      - db
  db:
    container_name: postgresql_bue_prod
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bue_strenge_gemmer
      - POSTGRES_PASSWORD=bue_strenge_gemmer
      - POSTGRES_DB=bue_strenge_gemmer_prod
  redis:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume: {}