FROM python:3.8.3-alpine

WORKDIR /usr/src/backend

ADD ./requirements.txt .

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev
    
RUN pip3 install --upgrade pip
RUN pip3 install gunicorn
RUN pip3 install -r requirements.txt

COPY . .

ENTRYPOINT [ "./wsgi-entrypoint.sh" ]