FROM python:3.8.3-alpine as builder

WORKDIR /app
ADD ./backend/requirements.txt /app/backend/

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# lint
RUN pip install --upgrade pip
RUN pip install flake8
RUN pip install gunicorn
RUN pip install djangorestframework 
RUN pip install -r backend/requirements.txt

ADD ./ /app/
ADD ./backend /app/backend 